### ISSUE TITLE
Resolve Git Gateway auth issue

### ISSUE THREAD

**Issue by amme2** [amme2/tw-hugo-cms#3]
Website is deployed to https://vigorous-boyd-c9e9ce.netlify.app/ but since merging #2 trying to log in as admin results in:

![image](https://user-images.githubusercontent.com/41161695/106054589-271db380-60e4-11eb-910c-52f5355133cc.png)

There's a thread about this [here](https://community.netlify.com/t/git-gateway-error/12220). I've tried disabling and re-enabling Git Gateway several times to no avail. I also changed the deploy contexts' production branch to 'main' only, rather than 'master' as originally set, but again the same Git Gateway error message appears.

**Comment by amme2** [comment]
Redeployed successfully but now I don't even get the error message - just a completely blank window!

**Comment by chrisdaaz** [comment]
Ah, I see. The website now needs to be able to connect to your github repository through an API protocol called OAuth. There are instructions on how to do this here (without this setup, the javacript that is supposed to render the login screen fails to load, which is why we have a blank screen): https://docs.netlify.com/visitor-access/oauth-provider-tokens/#using-an-authentication-provider

These steps require you to change settings in both the [GitHub repository](https://docs.github.com/en/developers/apps/creating-an-oauth-app) and [Netlify Dashboard](https://app.netlify.com)

@amme2

**Comment by chrisdaaz** [comment]
To clarify, this set up will use GitHub as the backend. Once it's setup, anyone with access to your github repository via their github username and password will be able to login to the cms to make / edit pages.

**Comment by amme2** [comment]
@chrisdaaz thank you. I've done all of that but I'm still getting a blank screen I'm afraid. 

I see what you meant about the authentication setup being difficult!

**Comment by chrisdaaz** [comment]
silly question but did you add `https://vigorous-boyd-c9e9ce.netlify.app/` for the `Homepage URL` ?

**Comment by amme2** [comment]
Yep:

![image](https://user-images.githubusercontent.com/41161695/106060907-913a5680-60ec-11eb-908d-cdb9e11da909.png)

**Comment by amme2** [comment]
Have also tried in another browser in case it was some kind of caching issue. Same result :-(

To clarify from my end, https://vigorous-boyd-c9e9ce.netlify.app/admin/ is correct?

**Comment by chrisdaaz** [comment]
Yes, that all looks correct.

I'm looking into this (which seems like a script source security thing): 

![image](https://user-images.githubusercontent.com/24395592/106061482-0b51e780-60bb-11eb-866a-110b1f44cc2c.png)

I'll report back soon.

**Comment by amme2** [comment]
Thank you (and sorry!).

**Comment by chrisdaaz** [comment]
No worries! I submitted a fix that i hope will work https://github.com/amme2/tw-hugo-cms/pull/4

**Comment by amme2** [comment]
Yes that worked. Thank you! 

Cannot see any of the sample content in there though, so that's this evening's path of investigation I guess...
